### ISSUE TITLE
Setting for treating additional extensions as plain text

### ISSUE THREAD

**Issue by keithadams** [vrtmrz/obsidian-screwdriver#2]
It'd be great if we could add extensions to the list of files treated as plain text. Ideally it could be defined in the frontmatter to tell Screwdriver to treat the files as plain text.

For example, I'd like to dump and restore the file "obsidian.vimrc" that I use with the [Obsidian Vimrc Support Plugin](https://github.com/esm7/obsidian-vimrc-support). Currently, Screwdriver doesn't dump it as plain text:

````
```Meta/Scripts/obsidian.vimrc
IiB5YW5rIHRvIHN5c3RlbSBjbGlwYm9hcmQKc2V0IGNsaXBib2FyZD11bm5hbWVk
```
````

I'm assuming only the extensions defined [here](https://github.com/vrtmrz/obsidian-screwdriver/blob/main/main.ts#L42) are treated as plain text.

**Comment by vrtmrz** [comment]
Thank you for requesting the new feature! 
I made the option but it sometimes broke my file by binary data.
So instead of that, I made a file-type detection the same as fetching files from the web. And saved data now contains their type.

Could you please try v0.0.5?

**Comment by keithadams** [comment]
Yes, it works perfectly. Thanks for adding the feature!

**Comment by vrtmrz** [comment]
You are welcome! I am very happy to hear that!
