### ISSUE TITLE
Question on targets

### ISSUE THREAD

**Issue by YayoAstur** [vrtmrz/obsidian-screwdriver#4]
Hi!
Is it posible to set a target outside the Obsidian folder? e.g. C:\Users\USER\AppData\Roaming\folder 
I would like to use it to backup and sync some app config by using obsidian between two devices. I've tried using 
```
 targets:
  - "C:\Users\USER\AppData\Roaming\app\config"`
```
```
 targets:
  - C:\Users\USER\AppData\Roaming\app\config`
```
But didn't manage to make it work...

TIA!

**Comment by vrtmrz** [comment]
Thank you for asking me!
However, I regret to say that referring files outside the vault cannot be handled.
Sorry that the plug-in did not meet your expectations.

**Comment by YayoAstur** [comment]
Thanks for answering and for the plugin! I'll definitely keep it as it helps me syncing some obsidian plugin data that its not currently handled on my current sync setup. 
Thanks again!
